include:
  - _pages

lang: en-US
name:
  full: Calvin Kosmatka
  given: Calvin
  family: Kosmatka
github_username: calvinkosmatka

affiliations: University of Wisconsinâ€”Madison
nav_right:
  - href: /resources
    title: Resources
  - href: /
    title: About
